---
# tasks file for mysqlbinlog
- name: Stop MySQL Service
  service:
    name: mysqld
    state: stopped

- name: Install python3
  ansible.builtin.dnf:
    name: python3-pip
    state: present

- name: Install PyMySQL
  pip:
    name: pymysql
    state: present

- name: Update MySQL configuration to bin-log
  lineinfile:
    path: /etc/my.cnf
    regexp: '^log-bin='
    line: 'log-bin=/var/log/mysql/mysql-bin.log'
    state: present

- name: Start MySQL Service
  service:
    name: mysqld
    state: started
  notify: restart mysql
