---
# tasks file for mysql

- name: Install MySQL client package
  yum:
    name: mysql-server
    state: present

- name: do permit traffic in default zone on port {{ mysql_port }}/tcp
  ansible.posix.firewalld:
    port: "{{mysql_port}}/tcp"
    permanent: true
    state: enabled
  
- name: Stop MySQL service
  systemd:
    name: mysqld
    state: stopped
  
- name: Update MySQL configuration file
  lineinfile:
    path: /etc/my.cnf
    regexp: '^port='
    line: 'port={{ mysql_port }}'
    state: present
  
- name: Start MySQL service
  systemd:
    name: mysqld
    state: started
  notify: restart mysql

