---
- name: Change Apache port to 18111
  hosts: web
  become: true
  user: root

  roles:
    - apache
    
- name: Change MySQL Port
  hosts: db
  become: true

  roles:
    - mysql

- name: Change Hostname

  hosts: hostname
  become: true
  roles: 
    - hostname

- name: Set MySQL to binary logging

  hosts: db
  become: true
  roles:
    - mysqlbinlog  
